# Urban Mobility App - Analysis Options
# Configurações de análise de código para garantir qualidade e consistência

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/l10n/"
    - "build/**"
    - "lib/generated_plugin_registrant.dart"
  
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat missing returns as errors
    missing_return: error
    # Treat invalid assignments as errors
    invalid_assignment: error
    # Treat dead code as warnings
    dead_code: warning
    # Treat unused imports as warnings
    unused_import: warning
    # Treat unused local variables as warnings
    unused_local_variable: warning

linter:
  rules:
    # Regras de qualidade essenciais
    - avoid_print
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - use_key_in_widget_constructors
    - sort_child_properties_last
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - curly_braces_in_flow_control_structures
    - empty_constructor_bodies
    - file_names
    - flutter_style_todos
    - library_names
    - library_prefixes
    - no_logic_in_create_state
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_final_fields
    - prefer_final_locals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_null_aware_operators
    - prefer_relative_imports
    - sort_constructors_first
    - type_annotate_public_apis
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - use_rethrow_when_possible
    - void_checks
